// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js reads .env.local on its own, but the Prisma CLI does not — it only
// loads .env. Without this, `prisma migrate` and `prisma db seed` start with no
// DATABASE_URL and fail before they reach the database.
loadEnv({ path: [".env.local", ".env"], quiet: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Onboarding is manual: there is no self-serve signup, so the first
    // Organization and its OWNER are created here rather than through the app.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
